---
- name: Updating Packages
  shell: yum update -y
  ignore_errors: yes

- name: installing Python3
  shell: yum install python3 -y
  ignore_errors: yes

- name: Install PIP3
  shell: yum install python3-pip -y
  ignore_errors: yes

- name: Install boto3
  shell: pip3 install boto3
  ignore_errors: yes

- name: Link python3 with python
  shell: ln -s /bin/python3 /bin/python
  ignore_errors: yes

- name: Mount /tmp dir for compose
  shell: mount /tmp -o remount,exec 
  ignore_errors: yes


