---
- name: Deploying Components on Dev Server
  hosts: server
  become: true
  vars_files:
    - vars/defaults.yml
    - vars/app.yml
  tasks:
    - name: Shut down docker compose if running
      shell: "cd {{ INSTALL_DIR }}/{{ PROJECT_NAME }}/ && sudo docker-compose down"
    - name: Clean volumes
      shell: "docker volume prune -f "
    - name: Clean images
      shell: "docker image prune -f "
    - name: Clean directory
      file:
        path: "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}"
        state: absent
