---
- name: Upgrade Packages
  shell: apt update -y
  ignore_errors: yes

- name: Install Python
  shell: apt-get install -y python
  ignore_errors: yes

- name: Install PIP3
  shell: apt install -y python3-pip
  ignore_errors: yes

- name: Install boto3
  shell: pip3 install boto3
  ignore_errors: yes

- name: Link python3 with python
  shell: ln -s /bin/python3 /bin/python
  ignore_errors: yes

- name: Mount /tmp dir for compose
  shell: mount /tmp -o remount,exec 
  ignore_errors: yes