---
### Installation Directory Structure 
PACKAGES:
  - yum-utils
  - wget
  - rpm
  - epel-release

GROUP: "devopsadmin"
OWNER: "devopsadmin"

INSTALL_DIR: "/app"
PROJECT_NAME: "apps"
PROJECT_ROOT_SUBDIRS:
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/db_data"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/logs"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/properties"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/offline_data"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/certs"

ROOT_LOGS_SUBDIRS:
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/logs/ui"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/logs/customapi"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/logs/mongodb" 
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/logs/jira_processor"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/logs/nonjira_processor"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/logs/azure_processor"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/logs/nonazureboards_processor"
  
OFFLINE_DATA_SUBDIR:
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/offline_data/excel"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/offline_data/offline_json"

OFFLINE_DATA_EXCEL:
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/offline_data/excel/capacity"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/offline_data/excel/engg_maturity"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/offline_data/excel/engg_maturity_master"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/offline_data/excel/project_offline_data"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/offline_data/excel/test_automation"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/offline_data/excel/capacity/scrum"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/offline_data/excel/capacity/kanban"

OFFLINE_DATA_JSON:
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/offline_data/offline_json/jira"
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/offline_data/offline_json/sonar" 
  - "{{ INSTALL_DIR }}/{{ PROJECT_NAME }}/offline_data/offline_json/new_relic"